<?php

use Illuminate\Database\Seeder;

class StateTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');

        DB::table('states')->delete();
        DB::table('states')->truncate();
        //african regions
        $regions = array();

        $regions[] = ["id" => 1, "country_id" => 1, "name" => "Adrar"];
        $regions[] = ["id" => 2, "country_id" => 1, "name" => "Chlef"];
        $regions[] = ["id" => 3, "country_id" => 1, "name" => "Laghouat"];
        $regions[] = ["id" => 4, "country_id" => 1, "name" => "Oum el-Bouaghi"];
        $regions[] = ["id" => 5, "country_id" => 1, "name" => "Batna"];
        $regions[] = ["id" => 6, "country_id" => 1, "name" => "Béjaïa"];
        $regions[] = ["id" => 7, "country_id" => 1, "name" => "Biskra"];
        $regions[] = ["id" => 8, "country_id" => 1, "name" => "Béchar"];
        $regions[] = ["id" => 9, "country_id" => 1, "name" => "Blida"];
        $regions[] = ["id" => 10, "country_id" => 1, "name" => "Bouira"];
        $regions[] = ["id" => 11, "country_id" => 1, "name" => "Tamanghasset"];
        $regions[] = ["id" => 12, "country_id" => 1, "name" => "Tébessa"];
        $regions[] = ["id" => 13, "country_id" => 1, "name" => "Tlemcen"];
        $regions[] = ["id" => 14, "country_id" => 1, "name" => "Tiaret"];
        $regions[] = ["id" => 15, "country_id" => 1, "name" => "Tizi Ouzou"];
        $regions[] = ["id" => 16, "country_id" => 1, "name" => "Algiers"];
        $regions[] = ["id" => 17, "country_id" => 1, "name" => "Djelfa"];
        $regions[] = ["id" => 18, "country_id" => 1, "name" => "Jijel"];
        $regions[] = ["id" => 19, "country_id" => 1, "name" => "Sétif"];
        $regions[] = ["id" => 20, "country_id" => 1, "name" => "Saïda"];
        $regions[] = ["id" => 21, "country_id" => 1, "name" => "Skikda"];
        $regions[] = ["id" => 22, "country_id" => 1, "name" => "Sidi Bel Abbes"];
        $regions[] = ["id" => 23, "country_id" => 1, "name" => "Annaba"];
        $regions[] = ["id" => 24, "country_id" => 1, "name" => "Guelma"];
        $regions[] = ["id" => 25, "country_id" => 1, "name" => "Constantine"];
        $regions[] = ["id" => 26, "country_id" => 1, "name" => "Médéa"];
        $regions[] = ["id" => 27, "country_id" => 1, "name" => "Mostaganem"];
        $regions[] = ["id" => 28, "country_id" => 1, "name" => "M'Sila"];
        $regions[] = ["id" => 29, "country_id" => 1, "name" => "Mascara"];
        $regions[] = ["id" => 30, "country_id" => 1, "name" => "Ouargla"];
        $regions[] = ["id" => 31, "country_id" => 1, "name" => "Oran"];
        $regions[] = ["id" => 32, "country_id" => 1, "name" => "El Bayadh"];
        $regions[] = ["id" => 33, "country_id" => 1, "name" => "Illizi"];
        $regions[] = ["id" => 34, "country_id" => 1, "name" => "Bordj Bou Arréridj"];
        $regions[] = ["id" => 35, "country_id" => 1, "name" => "Boumerdès"];
        $regions[] = ["id" => 36, "country_id" => 1, "name" => "El Taref"];
        $regions[] = ["id" => 37, "country_id" => 1, "name" => "Tindouf"];
        $regions[] = ["id" => 38, "country_id" => 1, "name" => "Tissemsilt"];
        $regions[] = ["id" => 39, "country_id" => 1, "name" => "El Oued"];
        $regions[] = ["id" => 40, "country_id" => 1, "name" => "Khenchela"];
        $regions[] = ["id" => 41, "country_id" => 1, "name" => "Souk Ahras"];
        $regions[] = ["id" => 42, "country_id" => 1, "name" => "Tipasa"];
        $regions[] = ["id" => 43, "country_id" => 1, "name" => "Mila"];
        $regions[] = ["id" => 44, "country_id" => 1, "name" => "Aïn Defla"];
        $regions[] = ["id" => 45, "country_id" => 1, "name" => "Naama"];
        $regions[] = ["id" => 46, "country_id" => 1, "name" => "Aïn Témouchent"];
        $regions[] = ["id" => 47, "country_id" => 1, "name" => "Ghardaïa"];
        $regions[] = ["id" => 48, "country_id" => 1, "name" => "Relizane"];
        $regions[] = ["id" => 49, "country_id" => 2, "name" => "Bengo"];
        $regions[] = ["id" => 50, "country_id" => 2, "name" => "Benguela"];
        $regions[] = ["id" => 51, "country_id" => 2, "name" => "Bié"];
        $regions[] = ["id" => 52, "country_id" => 2, "name" => "Cabinda"];
        $regions[] = ["id" => 53, "country_id" => 2, "name" => "Cuando Cubango"];
        $regions[] = ["id" => 54, "country_id" => 2, "name" => "Cuanza Norte"];
        $regions[] = ["id" => 55, "country_id" => 2, "name" => "Cuanza Sul"];
        $regions[] = ["id" => 56, "country_id" => 2, "name" => "Cunene"];
        $regions[] = ["id" => 57, "country_id" => 2, "name" => "Huambo"];
        $regions[] = ["id" => 58, "country_id" => 2, "name" => "Huíla"];
        $regions[] = ["id" => 59, "country_id" => 2, "name" => "Luanda"];
        $regions[] = ["id" => 60, "country_id" => 2, "name" => "Lunda Norte"];
        $regions[] = ["id" => 61, "country_id" => 2, "name" => "Lunda Sul"];
        $regions[] = ["id" => 62, "country_id" => 2, "name" => "Malanje"];
        $regions[] = ["id" => 63, "country_id" => 2, "name" => "Moxico"];
        $regions[] = ["id" => 64, "country_id" => 2, "name" => "Namibe"];
        $regions[] = ["id" => 65, "country_id" => 2, "name" => "Uíge"];
        $regions[] = ["id" => 66, "country_id" => 2, "name" => "Zaire"];
        $regions[] = ["id" => 67, "country_id" => 3, "name" => "Alibori"];
        $regions[] = ["id" => 68, "country_id" => 3, "name" => "Atakora"];
        $regions[] = ["id" => 69, "country_id" => 3, "name" => "Atlanyique"];
        $regions[] = ["id" => 70, "country_id" => 3, "name" => "Borgou"];
        $regions[] = ["id" => 71, "country_id" => 3, "name" => "Collines"];
        $regions[] = ["id" => 72, "country_id" => 3, "name" => "Donga"];
        $regions[] = ["id" => 73, "country_id" => 3, "name" => "Kouffo"];
        $regions[] = ["id" => 74, "country_id" => 3, "name" => "Littoral"];
        $regions[] = ["id" => 75, "country_id" => 3, "name" => "Mono"];
        $regions[] = ["id" => 76, "country_id" => 3, "name" => "Oueme"];
        $regions[] = ["id" => 77, "country_id" => 3, "name" => "Plateau"];
        $regions[] = ["id" => 78, "country_id" => 3, "name" => "Zou"];
        $regions[] = ["id" => 79, "country_id" => 4, "name" => "Central"];
        $regions[] = ["id" => 80, "country_id" => 4, "name" => "Ghanzi"];
        $regions[] = ["id" => 81, "country_id" => 4, "name" => "Kgalagadi"];
        $regions[] = ["id" => 82, "country_id" => 4, "name" => "Kgatleng"];
        $regions[] = ["id" => 83, "country_id" => 4, "name" => "Kweneng"];
        $regions[] = ["id" => 84, "country_id" => 4, "name" => "North-East"];
        $regions[] = ["id" => 85, "country_id" => 4, "name" => "North-West"];
        $regions[] = ["id" => 86, "country_id" => 4, "name" => "South-East"];
        $regions[] = ["id" => 87, "country_id" => 4, "name" => "Southern"];
        $regions[] = ["id" => 88, "country_id" => 5, "name" => "Boucle du Mouhoun"];
        $regions[] = ["id" => 89, "country_id" => 5, "name" => "Cascades"];
        $regions[] = ["id" => 90, "country_id" => 5, "name" => "Centre"];
        $regions[] = ["id" => 91, "country_id" => 5, "name" => "Centre-Est"];
        $regions[] = ["id" => 92, "country_id" => 5, "name" => "Centre-Nord"];
        $regions[] = ["id" => 93, "country_id" => 5, "name" => "Centre-Ouest"];
        $regions[] = ["id" => 94, "country_id" => 5, "name" => "Centre-Sud"];
        $regions[] = ["id" => 95, "country_id" => 5, "name" => "Est"];
        $regions[] = ["id" => 96, "country_id" => 5, "name" => "Hauts-Bassins"];
        $regions[] = ["id" => 97, "country_id" => 5, "name" => "Nord"];
        $regions[] = ["id" => 98, "country_id" => 5, "name" => "Plateau-Central"];
        $regions[] = ["id" => 99, "country_id" => 6, "name" => "Bubanza"];
        $regions[] = ["id" => 100, "country_id" => 6, "name" => "Bujumbura"];
        $regions[] = ["id" => 101, "country_id" => 6, "name" => "Bururi"];
        $regions[] = ["id" => 102, "country_id" => 6, "name" => "Cankuzo"];
        $regions[] = ["id" => 103, "country_id" => 6, "name" => "Cibitoke"];
        $regions[] = ["id" => 104, "country_id" => 6, "name" => "Gitega"];
        $regions[] = ["id" => 105, "country_id" => 6, "name" => "Karuzi"];
        $regions[] = ["id" => 106, "country_id" => 6, "name" => "Kayanza"];
        $regions[] = ["id" => 107, "country_id" => 6, "name" => "Kirundo"];
        $regions[] = ["id" => 108, "country_id" => 6, "name" => "Makamba"];
        $regions[] = ["id" => 109, "country_id" => 6, "name" => "Muramvya"];
        $regions[] = ["id" => 110, "country_id" => 6, "name" => "Muyinga"];
        $regions[] = ["id" => 111, "country_id" => 6, "name" => "Mwaro"];
        $regions[] = ["id" => 112, "country_id" => 6, "name" => "Ngozi"];
        $regions[] = ["id" => 113, "country_id" => 6, "name" => "Rutana"];
        $regions[] = ["id" => 114, "country_id" => 6, "name" => "Ruyigi"];
        $regions[] = ["id" => 115, "country_id" => 7, "name" => "Adamaoua"];
        $regions[] = ["id" => 116, "country_id" => 7, "name" => "Centre"];
        $regions[] = ["id" => 117, "country_id" => 7, "name" => "East"];
        $regions[] = ["id" => 118, "country_id" => 7, "name" => "Far North"];
        $regions[] = ["id" => 119, "country_id" => 7, "name" => "Littoral"];
        $regions[] = ["id" => 120, "country_id" => 7, "name" => "North"];
        $regions[] = ["id" => 121, "country_id" => 7, "name" => "Northwest"];
        $regions[] = ["id" => 122, "country_id" => 7, "name" => "South"];
        $regions[] = ["id" => 123, "country_id" => 7, "name" => "Southwest"];
        $regions[] = ["id" => 124, "country_id" => 7, "name" => "West"];
        $regions[] = ["id" => 125, "country_id" => 8, "name" => "Boa Vista"];
        $regions[] = ["id" => 126, "country_id" => 8, "name" => "Brava"];
        $regions[] = ["id" => 127, "country_id" => 8, "name" => "Maio"];
        $regions[] = ["id" => 128, "country_id" => 8, "name" => "Mosteiros"];
        $regions[] = ["id" => 129, "country_id" => 8, "name" => "Paul"];
        $regions[] = ["id" => 130, "country_id" => 8, "name" => "Praia"];
        $regions[] = ["id" => 131, "country_id" => 8, "name" => "Ribeira Grande"];
        $regions[] = ["id" => 132, "country_id" => 8, "name" => "Sal"];
        $regions[] = ["id" => 133, "country_id" => 8, "name" => "Santa Catarina"];
        $regions[] = ["id" => 134, "country_id" => 8, "name" => "Santa Cruz"];
        $regions[] = ["id" => 135, "country_id" => 8, "name" => "São Domingos"];
        $regions[] = ["id" => 136, "country_id" => 8, "name" => "São Filipe"];
        $regions[] = ["id" => 137, "country_id" => 8, "name" => "São Miguel"];
        $regions[] = ["id" => 138, "country_id" => 8, "name" => "Sao Nicolau"];
        $regions[] = ["id" => 139, "country_id" => 8, "name" => "São Vicente"];
        $regions[] = ["id" => 140, "country_id" => 8, "name" => "Tarrafal"];
        $regions[] = ["id" => 141, "country_id" => 9, "name" => "Bamingui-Bangoran"];
        $regions[] = ["id" => 142, "country_id" => 9, "name" => "Bangui"];
        $regions[] = ["id" => 143, "country_id" => 9, "name" => "Basse-Kotto"];
        $regions[] = ["id" => 144, "country_id" => 9, "name" => "Cuvette-Ouest"];
        $regions[] = ["id" => 145, "country_id" => 9, "name" => "Haute-Kotto"];
        $regions[] = ["id" => 146, "country_id" => 9, "name" => "Haut-Mbomou"];
        $regions[] = ["id" => 147, "country_id" => 9, "name" => "Kémo"];
        $regions[] = ["id" => 148, "country_id" => 9, "name" => "Lobaye"];
        $regions[] = ["id" => 149, "country_id" => 9, "name" => "Mambéré-Kadéï"];
        $regions[] = ["id" => 150, "country_id" => 9, "name" => "Mbomou"];
        $regions[] = ["id" => 151, "country_id" => 9, "name" => "Nana-Grébizi"];
        $regions[] = ["id" => 152, "country_id" => 9, "name" => "Nana-Mambéré"];
        $regions[] = ["id" => 153, "country_id" => 9, "name" => "Ombella-Mpoko"];
        $regions[] = ["id" => 154, "country_id" => 9, "name" => "Ouaka"];
        $regions[] = ["id" => 155, "country_id" => 9, "name" => "Ouham"];
        $regions[] = ["id" => 156, "country_id" => 9, "name" => "Ouham-Pendé"];
        $regions[] = ["id" => 157, "country_id" => 9, "name" => "Sangha-Mbaéré"];
        $regions[] = ["id" => 158, "country_id" => 10, "name" => "Batha"];
        $regions[] = ["id" => 159, "country_id" => 10, "name" => "Biltine"];
        $regions[] = ["id" => 160, "country_id" => 10, "name" => "Borkou-Ennedi-Tibesti"];
        $regions[] = ["id" => 161, "country_id" => 10, "name" => "Chari-Baguirmi"];
        $regions[] = ["id" => 162, "country_id" => 10, "name" => "Guéra"];
        $regions[] = ["id" => 163, "country_id" => 10, "name" => "Kanem"];
        $regions[] = ["id" => 164, "country_id" => 10, "name" => "Lac"];
        $regions[] = ["id" => 165, "country_id" => 10, "name" => "Logone Occidental"];
        $regions[] = ["id" => 166, "country_id" => 10, "name" => "Logone Oriental"];
        $regions[] = ["id" => 167, "country_id" => 10, "name" => "Mayo-Kébbi"];
        $regions[] = ["id" => 168, "country_id" => 10, "name" => "Moyen-Chari"];
        $regions[] = ["id" => 169, "country_id" => 10, "name" => "Ouaddaï"];
        $regions[] = ["id" => 170, "country_id" => 10, "name" => "Salamat"];
        $regions[] = ["id" => 171, "country_id" => 10, "name" => "Tandjilé"];
        $regions[] = ["id" => 172, "country_id" => 11, "name" => "Anjouan"];
        $regions[] = ["id" => 173, "country_id" => 11, "name" => "Grande Comore"];
        $regions[] = ["id" => 174, "country_id" => 11, "name" => "Mwali"];
        $regions[] = ["id" => 175, "country_id" => 12, "name" => "Bandundu"];
        $regions[] = ["id" => 176, "country_id" => 12, "name" => "Bas-Congo"];
        $regions[] = ["id" => 177, "country_id" => 12, "name" => "Équateur"];
        $regions[] = ["id" => 178, "country_id" => 12, "name" => "Kasaï-Oriental"];
        $regions[] = ["id" => 179, "country_id" => 12, "name" => "Katanga"];
        $regions[] = ["id" => 180, "country_id" => 12, "name" => "Kinshasa"];
        $regions[] = ["id" => 181, "country_id" => 12, "name" => "Maniema"];
        $regions[] = ["id" => 182, "country_id" => 12, "name" => "Nord-Kivu"];
        $regions[] = ["id" => 183, "country_id" => 12, "name" => "Orientale"];
        $regions[] = ["id" => 184, "country_id" => 12, "name" => "Sud-Kivu"];
        $regions[] = ["id" => 185, "country_id" => 13, "name" => "Bouenza"];
        $regions[] = ["id" => 186, "country_id" => 13, "name" => "Brazzaville"];
        $regions[] = ["id" => 187, "country_id" => 13, "name" => "Cuvette"];
        $regions[] = ["id" => 188, "country_id" => 13, "name" => "Cuvette-Ouest"];
        $regions[] = ["id" => 189, "country_id" => 13, "name" => "Kouilou"];
        $regions[] = ["id" => 190, "country_id" => 13, "name" => "Lékoumou"];
        $regions[] = ["id" => 191, "country_id" => 13, "name" => "Likouala"];
        $regions[] = ["id" => 192, "country_id" => 13, "name" => "Niari"];
        $regions[] = ["id" => 193, "country_id" => 13, "name" => "Plateaux"];
        $regions[] = ["id" => 194, "country_id" => 13, "name" => "Pool"];
        $regions[] = ["id" => 195, "country_id" => 13, "name" => "Sangha"];
        $regions[] = ["id" => 196, "country_id" => 14, "name" => "Agnéby"];
        $regions[] = ["id" => 197, "country_id" => 14, "name" => "Bafing"];
        $regions[] = ["id" => 198, "country_id" => 14, "name" => "Bas-Sassandra"];
        $regions[] = ["id" => 199, "country_id" => 14, "name" => "Denguélé"];
        $regions[] = ["id" => 200, "country_id" => 14, "name" => "Dix-Huit Montagnes"];
        $regions[] = ["id" => 201, "country_id" => 14, "name" => "Fromager"];
        $regions[] = ["id" => 202, "country_id" => 14, "name" => "Haut-Sassandra"];
        $regions[] = ["id" => 203, "country_id" => 14, "name" => "Lacs"];
        $regions[] = ["id" => 204, "country_id" => 14, "name" => "Lagunes"];
        $regions[] = ["id" => 205, "country_id" => 14, "name" => "Marahoué"];
        $regions[] = ["id" => 206, "country_id" => 14, "name" => "Moyen-Cavally"];
        $regions[] = ["id" => 207, "country_id" => 14, "name" => "Moyen-Comoé"];
        $regions[] = ["id" => 208, "country_id" => 14, "name" => "N'zi-Comoe"];
        $regions[] = ["id" => 209, "country_id" => 14, "name" => "Savanes"];
        $regions[] = ["id" => 210, "country_id" => 14, "name" => "Sud-Bandama"];
        $regions[] = ["id" => 211, "country_id" => 14, "name" => "Sud-Comoé"];
        $regions[] = ["id" => 212, "country_id" => 14, "name" => "Vallée du Bandama"];
        $regions[] = ["id" => 213, "country_id" => 14, "name" => "Worodougou"];
        $regions[] = ["id" => 214, "country_id" => 14, "name" => "Zanzan"];
        $regions[] = ["id" => 215, "country_id" => 15, "name" => "Ali Sabieh"];
        $regions[] = ["id" => 216, "country_id" => 15, "name" => "Tadjourah"];
        $regions[] = ["id" => 217, "country_id" => 15, "name" => "Obock"];
        $regions[] = ["id" => 218, "country_id" => 15, "name" => "Dikhil"];
        $regions[] = ["id" => 219, "country_id" => 15, "name" => "Arta"];
        $regions[] = ["id" => 220, "country_id" => 16, "name" => "Matruh"];
        $regions[] = ["id" => 221, "country_id" => 16, "name" => "Alexandria"];
        $regions[] = ["id" => 222, "country_id" => 16, "name" => "Beheira"];
        $regions[] = ["id" => 223, "country_id" => 16, "name" => "Kafr el-Sheikh"];
        $regions[] = ["id" => 224, "country_id" => 16, "name" => "Dakahlia"];
        $regions[] = ["id" => 225, "country_id" => 16, "name" => "Damietta"];
        $regions[] = ["id" => 226, "country_id" => 16, "name" => "Port Said"];
        $regions[] = ["id" => 227, "country_id" => 16, "name" => "North Sinai"];
        $regions[] = ["id" => 228, "country_id" => 16, "name" => "Gharbia"];
        $regions[] = ["id" => 229, "country_id" => 16, "name" => "Monufia"];
        $regions[] = ["id" => 230, "country_id" => 16, "name" => "Qalyubia"];
        $regions[] = ["id" => 231, "country_id" => 16, "name" => "Sharqia"];
        $regions[] = ["id" => 232, "country_id" => 16, "name" => "Ismailia"];
        $regions[] = ["id" => 233, "country_id" => 16, "name" => "Giza"];
        $regions[] = ["id" => 234, "country_id" => 16, "name" => "Faiyum"];
        $regions[] = ["id" => 235, "country_id" => 16, "name" => "Cairo"];
        $regions[] = ["id" => 236, "country_id" => 16, "name" => "Suez"];
        $regions[] = ["id" => 237, "country_id" => 16, "name" => "South Sinai"];
        $regions[] = ["id" => 238, "country_id" => 16, "name" => "Beni Suef"];
        $regions[] = ["id" => 239, "country_id" => 16, "name" => "Minya"];
        $regions[] = ["id" => 240, "country_id" => 16, "name" => "New Valley"];
        $regions[] = ["id" => 241, "country_id" => 16, "name" => "Asyut"];
        $regions[] = ["id" => 242, "country_id" => 16, "name" => "Red Sea"];
        $regions[] = ["id" => 243, "country_id" => 16, "name" => "Sohag"];
        $regions[] = ["id" => 244, "country_id" => 16, "name" => "Qena"];
        $regions[] = ["id" => 245, "country_id" => 16, "name" => "Luxor"];
        $regions[] = ["id" => 246, "country_id" => 16, "name" => "Aswan"];
        $regions[] = ["id" => 247, "country_id" => 17, "name" => "Annobón"];
        $regions[] = ["id" => 248, "country_id" => 17, "name" => "Bioko Norte"];
        $regions[] = ["id" => 249, "country_id" => 17, "name" => "Bioko Sur"];
        $regions[] = ["id" => 250, "country_id" => 17, "name" => "Centro Sur"];
        $regions[] = ["id" => 251, "country_id" => 17, "name" => "Kié-Ntem"];
        $regions[] = ["id" => 252, "country_id" => 17, "name" => "Litoral"];
        $regions[] = ["id" => 253, "country_id" => 17, "name" => "Wele-Nzas"];
        $regions[] = ["id" => 254, "country_id" => 18, "name" => "Ānseba"];
        $regions[] = ["id" => 255, "country_id" => 18, "name" => "Debub"];
        $regions[] = ["id" => 256, "country_id" => 18, "name" => "Debubawi K'eyih Bahri"];
        $regions[] = ["id" => 257, "country_id" => 18, "name" => "Gash Barka"];
        $regions[] = ["id" => 258, "country_id" => 18, "name" => "Ma'akel"];
        $regions[] = ["id" => 259, "country_id" => 18, "name" => "Semenawi K'eyih Bahri"];
        $regions[] = ["id" => 260, "country_id" => 19, "name" => "Ādīs Ābeba"];
        $regions[] = ["id" => 261, "country_id" => 19, "name" => "Afar"];
        $regions[] = ["id" => 262, "country_id" => 19, "name" => "Amara"];
        $regions[] = ["id" => 263, "country_id" => 19, "name" => "Binshangul Gumuz"];
        $regions[] = ["id" => 264, "country_id" => 19, "name" => "Dire Dawa"];
        $regions[] = ["id" => 265, "country_id" => 19, "name" => "Gambela Hizboch"];
        $regions[] = ["id" => 266, "country_id" => 19, "name" => "Hareri Hizb"];
        $regions[] = ["id" => 267, "country_id" => 19, "name" => "Oromiya"];
        $regions[] = ["id" => 268, "country_id" => 19, "name" => "Sumale"];
        $regions[] = ["id" => 269, "country_id" => 19, "name" => "Tigray"];
        $regions[] = ["id" => 270, "country_id" => 19, "name" => "YeDebub Biheroch Bihereseboch na Hizboch"];
        $regions[] = ["id" => 271, "country_id" => 20, "name" => "Estuaire"];
        $regions[] = ["id" => 272, "country_id" => 20, "name" => "Haut-Ogooué"];
        $regions[] = ["id" => 273, "country_id" => 20, "name" => "Moyen-Ogooué"];
        $regions[] = ["id" => 274, "country_id" => 20, "name" => "Ngounié"];
        $regions[] = ["id" => 275, "country_id" => 20, "name" => "Nyanga"];
        $regions[] = ["id" => 276, "country_id" => 20, "name" => "Ogooué-Ivindo"];
        $regions[] = ["id" => 277, "country_id" => 20, "name" => "Ogooué-Lolo"];
        $regions[] = ["id" => 278, "country_id" => 20, "name" => "Ogooué-Maritime"];
        $regions[] = ["id" => 279, "country_id" => 20, "name" => "Woleu-Ntem"];
        $regions[] = ["id" => 280, "country_id" => 21, "name" => "Banjul"];
        $regions[] = ["id" => 281, "country_id" => 21, "name" => "Central River"];
        $regions[] = ["id" => 282, "country_id" => 21, "name" => "Lower River"];
        $regions[] = ["id" => 283, "country_id" => 21, "name" => "North Bank"];
        $regions[] = ["id" => 284, "country_id" => 21, "name" => "Upper River"];
        $regions[] = ["id" => 285, "country_id" => 21, "name" => "Western"];
        $regions[] = ["id" => 286, "country_id" => 22, "name" => "Ashanti"];
        $regions[] = ["id" => 287, "country_id" => 22, "name" => "Brong-Ahafo"];
        $regions[] = ["id" => 288, "country_id" => 22, "name" => "Central"];
        $regions[] = ["id" => 289, "country_id" => 22, "name" => "Eastern"];
        $regions[] = ["id" => 290, "country_id" => 22, "name" => "Greater Accra"];
        $regions[] = ["id" => 291, "country_id" => 22, "name" => "Northern"];
        $regions[] = ["id" => 292, "country_id" => 22, "name" => "Upper East"];
        $regions[] = ["id" => 293, "country_id" => 22, "name" => "Upper West"];
        $regions[] = ["id" => 294, "country_id" => 22, "name" => "Volta"];
        $regions[] = ["id" => 295, "country_id" => 22, "name" => "Western"];
        $regions[] = ["id" => 296, "country_id" => 23, "name" => "National Capital"];
        $regions[] = ["id" => 297, "country_id" => 23, "name" => "Morobe"];
        $regions[] = ["id" => 298, "country_id" => 23, "name" => "North Solomons"];
        $regions[] = ["id" => 299, "country_id" => 23, "name" => "Southern Highlands"];
        $regions[] = ["id" => 300, "country_id" => 23, "name" => "East New Britain"];
        $regions[] = ["id" => 301, "country_id" => 23, "name" => "Northern"];
        $regions[] = ["id" => 302, "country_id" => 23, "name" => "Western Highlands"];
        $regions[] = ["id" => 303, "country_id" => 23, "name" => "Western"];
        $regions[] = ["id" => 304, "country_id" => 23, "name" => "Madang"];
        $regions[] = ["id" => 305, "country_id" => 23, "name" => "Eastern Highlands"];
        $regions[] = ["id" => 306, "country_id" => 23, "name" => "East Sepik"];
        $regions[] = ["id" => 307, "country_id" => 23, "name" => "West New Britain"];
        $regions[] = ["id" => 308, "country_id" => 23, "name" => "Sandaun"];
        $regions[] = ["id" => 309, "country_id" => 23, "name" => "New Ireland"];
        $regions[] = ["id" => 310, "country_id" => 23, "name" => "Milne Bay"];
        $regions[] = ["id" => 311, "country_id" => 23, "name" => "Chimbu"];
        $regions[] = ["id" => 312, "country_id" => 23, "name" => "Enga"];
        $regions[] = ["id" => 313, "country_id" => 23, "name" => "Manus"];
        $regions[] = ["id" => 314, "country_id" => 23, "name" => "Gulf"];
        $regions[] = ["id" => 315, "country_id" => 23, "name" => "Central"];
        $regions[] = ["id" => 316, "country_id" => 24, "name" => "Bafatá"];
        $regions[] = ["id" => 317, "country_id" => 24, "name" => "Biombo"];
        $regions[] = ["id" => 318, "country_id" => 24, "name" => "Bissau"];
        $regions[] = ["id" => 319, "country_id" => 24, "name" => "Bolama"];
        $regions[] = ["id" => 320, "country_id" => 24, "name" => "Cacheu"];
        $regions[] = ["id" => 321, "country_id" => 24, "name" => "Gabú"];
        $regions[] = ["id" => 322, "country_id" => 24, "name" => "Oio"];
        $regions[] = ["id" => 323, "country_id" => 24, "name" => "Quinara"];
        $regions[] = ["id" => 324, "country_id" => 24, "name" => "Tombali"];
        $regions[] = ["id" => 325, "country_id" => 25, "name" => "Central"];
        $regions[] = ["id" => 326, "country_id" => 25, "name" => "Coast"];
        $regions[] = ["id" => 327, "country_id" => 25, "name" => "Eastern"];
        $regions[] = ["id" => 328, "country_id" => 25, "name" => "Nairobi Area"];
        $regions[] = ["id" => 329, "country_id" => 25, "name" => "North-Eastern"];
        $regions[] = ["id" => 330, "country_id" => 25, "name" => "Nyanza"];
        $regions[] = ["id" => 331, "country_id" => 25, "name" => "Rift Valley"];
        $regions[] = ["id" => 332, "country_id" => 25, "name" => "Western"];
        $regions[] = ["id" => 333, "country_id" => 26, "name" => "Berea"];
        $regions[] = ["id" => 334, "country_id" => 26, "name" => "Butha-Buthe"];
        $regions[] = ["id" => 335, "country_id" => 26, "name" => "Leribe"];
        $regions[] = ["id" => 336, "country_id" => 26, "name" => "Mafeteng"];
        $regions[] = ["id" => 337, "country_id" => 26, "name" => "Maseru"];
        $regions[] = ["id" => 338, "country_id" => 26, "name" => "Mohaleʼs Hoek"];
        $regions[] = ["id" => 339, "country_id" => 26, "name" => "Mokhotlong"];
        $regions[] = ["id" => 340, "country_id" => 26, "name" => "Qachaʼs Nek"];
        $regions[] = ["id" => 341, "country_id" => 26, "name" => "Quthing"];
        $regions[] = ["id" => 342, "country_id" => 26, "name" => "Thaba-Tseka"];
        $regions[] = ["id" => 343, "country_id" => 27, "name" => "Bong"];
        $regions[] = ["id" => 344, "country_id" => 27, "name" => "Gbarpolu"];
        $regions[] = ["id" => 345, "country_id" => 27, "name" => "Grand Bassa"];
        $regions[] = ["id" => 346, "country_id" => 27, "name" => "Grand Cape Mount"];
        $regions[] = ["id" => 347, "country_id" => 27, "name" => "Grand Gedeh"];
        $regions[] = ["id" => 348, "country_id" => 27, "name" => "Lofa"];
        $regions[] = ["id" => 349, "country_id" => 27, "name" => "Margibi"];
        $regions[] = ["id" => 350, "country_id" => 27, "name" => "Maryland"];
        $regions[] = ["id" => 351, "country_id" => 27, "name" => "Monrovia"];
        $regions[] = ["id" => 352, "country_id" => 27, "name" => "Montserrado"];
        $regions[] = ["id" => 353, "country_id" => 27, "name" => "Nimba"];
        $regions[] = ["id" => 354, "country_id" => 27, "name" => "River Cess"];
        $regions[] = ["id" => 355, "country_id" => 27, "name" => "River Gee"];
        $regions[] = ["id" => 356, "country_id" => 27, "name" => "Sino"];
        $regions[] = ["id" => 357, "country_id" => 28, "name" => "Ajdabiya"];
        $regions[] = ["id" => 358, "country_id" => 28, "name" => "Al Aziziyah"];
        $regions[] = ["id" => 359, "country_id" => 28, "name" => "Al Fatih"];
        $regions[] = ["id" => 360, "country_id" => 28, "name" => "Al Jabal al Akhḑar"];
        $regions[] = ["id" => 361, "country_id" => 28, "name" => "Al Jufrah"];
        $regions[] = ["id" => 362, "country_id" => 28, "name" => "Al Khums"];
        $regions[] = ["id" => 363, "country_id" => 28, "name" => "Al Kufrah"];
        $regions[] = ["id" => 364, "country_id" => 28, "name" => "An Nuqāţ al Khams"];
        $regions[] = ["id" => 365, "country_id" => 28, "name" => "Ash Shati'"];
        $regions[] = ["id" => 366, "country_id" => 28, "name" => "Awbari"];
        $regions[] = ["id" => 367, "country_id" => 28, "name" => "Az Zāwiyah"];
        $regions[] = ["id" => 368, "country_id" => 28, "name" => "Banghāzī"];
        $regions[] = ["id" => 369, "country_id" => 28, "name" => "Darnah"];
        $regions[] = ["id" => 370, "country_id" => 28, "name" => "Ghadamis"];
        $regions[] = ["id" => 371, "country_id" => 28, "name" => "Gharyan"];
        $regions[] = ["id" => 372, "country_id" => 28, "name" => "Mişrātah"];
        $regions[] = ["id" => 373, "country_id" => 28, "name" => "Murzuq"];
        $regions[] = ["id" => 374, "country_id" => 28, "name" => "Sabhā"];
        $regions[] = ["id" => 375, "country_id" => 28, "name" => "Sawfajjin"];
        $regions[] = ["id" => 376, "country_id" => 28, "name" => "Surt"];
        $regions[] = ["id" => 377, "country_id" => 28, "name" => "Ţarābulus"];
        $regions[] = ["id" => 378, "country_id" => 28, "name" => "Tarhunah"];
        $regions[] = ["id" => 379, "country_id" => 28, "name" => "Tubruq"];
        $regions[] = ["id" => 380, "country_id" => 28, "name" => "Yafran"];
        $regions[] = ["id" => 381, "country_id" => 28, "name" => "Zlitan"];
        $regions[] = ["id" => 382, "country_id" => 29, "name" => "Antananarivo"];
        $regions[] = ["id" => 383, "country_id" => 29, "name" => "Antsiranana"];
        $regions[] = ["id" => 384, "country_id" => 29, "name" => "Fianarantsoa"];
        $regions[] = ["id" => 385, "country_id" => 29, "name" => "Mahajanga"];
        $regions[] = ["id" => 386, "country_id" => 29, "name" => "Toamasina"];
        $regions[] = ["id" => 387, "country_id" => 29, "name" => "Toliara"];
        $regions[] = ["id" => 388, "country_id" => 30, "name" => "Balaka"];
        $regions[] = ["id" => 389, "country_id" => 30, "name" => "Blantyre"];
        $regions[] = ["id" => 390, "country_id" => 30, "name" => "Chikwawa"];
        $regions[] = ["id" => 391, "country_id" => 30, "name" => "Chiradzulu"];
        $regions[] = ["id" => 392, "country_id" => 30, "name" => "Chitipa"];
        $regions[] = ["id" => 393, "country_id" => 30, "name" => "Dedza"];
        $regions[] = ["id" => 394, "country_id" => 30, "name" => "Dowa"];
        $regions[] = ["id" => 395, "country_id" => 30, "name" => "Karonga"];
        $regions[] = ["id" => 396, "country_id" => 30, "name" => "Kasungu"];
        $regions[] = ["id" => 397, "country_id" => 30, "name" => "Likoma"];
        $regions[] = ["id" => 398, "country_id" => 30, "name" => "Lilongwe"];
        $regions[] = ["id" => 399, "country_id" => 30, "name" => "Machinga"];
        $regions[] = ["id" => 400, "country_id" => 30, "name" => "Mangochi"];
        $regions[] = ["id" => 401, "country_id" => 30, "name" => "Mchinji"];
        $regions[] = ["id" => 402, "country_id" => 30, "name" => "Mulanje"];
        $regions[] = ["id" => 403, "country_id" => 30, "name" => "Mwanza"];
        $regions[] = ["id" => 404, "country_id" => 30, "name" => "Mzimba"];
        $regions[] = ["id" => 405, "country_id" => 30, "name" => "Nkhata Bay"];
        $regions[] = ["id" => 406, "country_id" => 30, "name" => "Nkhotakota"];
        $regions[] = ["id" => 407, "country_id" => 30, "name" => "Nsanje"];
        $regions[] = ["id" => 408, "country_id" => 30, "name" => "Ntcheu"];
        $regions[] = ["id" => 409, "country_id" => 30, "name" => "Ntchisi"];
        $regions[] = ["id" => 410, "country_id" => 30, "name" => "Phalombe"];
        $regions[] = ["id" => 411, "country_id" => 30, "name" => "Rumphi"];
        $regions[] = ["id" => 412, "country_id" => 30, "name" => "Salima"];
        $regions[] = ["id" => 413, "country_id" => 30, "name" => "Thyolo"];
        $regions[] = ["id" => 414, "country_id" => 30, "name" => "Zomba"];
        $regions[] = ["id" => 415, "country_id" => 31, "name" => "Bamako"];
        $regions[] = ["id" => 416, "country_id" => 31, "name" => "Gao"];
        $regions[] = ["id" => 417, "country_id" => 31, "name" => "Kayes"];
        $regions[] = ["id" => 418, "country_id" => 31, "name" => "Kidal"];
        $regions[] = ["id" => 419, "country_id" => 31, "name" => "Koulikoro"];
        $regions[] = ["id" => 420, "country_id" => 31, "name" => "Mopti"];
        $regions[] = ["id" => 421, "country_id" => 31, "name" => "Ségou"];
        $regions[] = ["id" => 422, "country_id" => 31, "name" => "Sikasso"];
        $regions[] = ["id" => 423, "country_id" => 31, "name" => "Tombouctou"];
        $regions[] = ["id" => 424, "country_id" => 32, "name" => "Adrar"];
        $regions[] = ["id" => 425, "country_id" => 32, "name" => "Assaba"];
        $regions[] = ["id" => 426, "country_id" => 32, "name" => "Brakna"];
        $regions[] = ["id" => 427, "country_id" => 32, "name" => "Dakhlet Nouadhibou"];
        $regions[] = ["id" => 428, "country_id" => 32, "name" => "Gorgol"];
        $regions[] = ["id" => 429, "country_id" => 32, "name" => "Guidimaka"];
        $regions[] = ["id" => 430, "country_id" => 32, "name" => "Hodh Ech Chargui"];
        $regions[] = ["id" => 431, "country_id" => 32, "name" => "Hodh El Gharbi"];
        $regions[] = ["id" => 432, "country_id" => 32, "name" => "Inchiri"];
        $regions[] = ["id" => 433, "country_id" => 32, "name" => "Tagant"];
        $regions[] = ["id" => 434, "country_id" => 32, "name" => "Tiris Zemmour"];
        $regions[] = ["id" => 435, "country_id" => 32, "name" => "Trarza"];
        $regions[] = ["id" => 436, "country_id" => 33, "name" => "Agalega Islands"];
        $regions[] = ["id" => 437, "country_id" => 33, "name" => "Black River"];
        $regions[] = ["id" => 438, "country_id" => 33, "name" => "Flacq"];
        $regions[] = ["id" => 439, "country_id" => 33, "name" => "Grand Port"];
        $regions[] = ["id" => 440, "country_id" => 33, "name" => "Moka"];
        $regions[] = ["id" => 441, "country_id" => 33, "name" => "Pamplemousses"];
        $regions[] = ["id" => 442, "country_id" => 33, "name" => "Plaines Wilhems"];
        $regions[] = ["id" => 443, "country_id" => 33, "name" => "Port Louis"];
        $regions[] = ["id" => 444, "country_id" => 33, "name" => "Rivière du Rempart"];
        $regions[] = ["id" => 445, "country_id" => 33, "name" => "Rodrigues"];
        $regions[] = ["id" => 446, "country_id" => 33, "name" => "Savanne"];
        $regions[] = ["id" => 447, "country_id" => 34, "name" => "Chaouia-Ouardigha"];
        $regions[] = ["id" => 448, "country_id" => 34, "name" => "Doukkala-Abda"];
        $regions[] = ["id" => 449, "country_id" => 34, "name" => "Fès-Boulemane"];
        $regions[] = ["id" => 450, "country_id" => 34, "name" => "Gharb-Chrarda-Beni Hssen"];
        $regions[] = ["id" => 451, "country_id" => 34, "name" => "Grand Casablanca"];
        $regions[] = ["id" => 452, "country_id" => 34, "name" => "Guelmim-Es Smara"];
        $regions[] = ["id" => 453, "country_id" => 34, "name" => "Marrakech-Tensift-Al Haouz"];
        $regions[] = ["id" => 454, "country_id" => 34, "name" => "Meknès-Tafilalet"];
        $regions[] = ["id" => 455, "country_id" => 34, "name" => "Oriental"];
        $regions[] = ["id" => 456, "country_id" => 34, "name" => "Rabat-Salé-Zemmour-Zaër"];
        $regions[] = ["id" => 457, "country_id" => 34, "name" => "Tadla-Azilal"];
        $regions[] = ["id" => 458, "country_id" => 34, "name" => "Tanger-Tétouan"];
        $regions[] = ["id" => 459, "country_id" => 34, "name" => "Taza-Al Hoceima-Taounate"];
        $regions[] = ["id" => 460, "country_id" => 35, "name" => "Cabo Delgado"];
        $regions[] = ["id" => 461, "country_id" => 35, "name" => "Gaza"];
        $regions[] = ["id" => 462, "country_id" => 35, "name" => "Inhambane"];
        $regions[] = ["id" => 463, "country_id" => 35, "name" => "Manica"];
        $regions[] = ["id" => 464, "country_id" => 35, "name" => "Maputo"];
        $regions[] = ["id" => 465, "country_id" => 35, "name" => "Nampula"];
        $regions[] = ["id" => 466, "country_id" => 35, "name" => "Niassa"];
        $regions[] = ["id" => 467, "country_id" => 35, "name" => "Sofala"];
        $regions[] = ["id" => 468, "country_id" => 35, "name" => "Tete"];
        $regions[] = ["id" => 469, "country_id" => 35, "name" => "Zambézia"];
        $regions[] = ["id" => 470, "country_id" => 36, "name" => "Bethanien"];
        $regions[] = ["id" => 471, "country_id" => 36, "name" => "Boesmanland"];
        $regions[] = ["id" => 472, "country_id" => 36, "name" => "Caprivi"];
        $regions[] = ["id" => 473, "country_id" => 36, "name" => "Damaraland"];
        $regions[] = ["id" => 474, "country_id" => 36, "name" => "Erongo"];
        $regions[] = ["id" => 475, "country_id" => 36, "name" => "Gobabis"];
        $regions[] = ["id" => 476, "country_id" => 36, "name" => "Grootfontein"];
        $regions[] = ["id" => 477, "country_id" => 36, "name" => "Hardap"];
        $regions[] = ["id" => 478, "country_id" => 36, "name" => "Kaokoland"];
        $regions[] = ["id" => 479, "country_id" => 36, "name" => "Karas"];
        $regions[] = ["id" => 480, "country_id" => 36, "name" => "Karasburg"];
        $regions[] = ["id" => 481, "country_id" => 36, "name" => "Karibib"];
        $regions[] = ["id" => 482, "country_id" => 36, "name" => "Kavango"];
        $regions[] = ["id" => 483, "country_id" => 36, "name" => "Keetmanshoop"];
        $regions[] = ["id" => 484, "country_id" => 36, "name" => "Kunene"];
        $regions[] = ["id" => 485, "country_id" => 36, "name" => "Luderitz"];
        $regions[] = ["id" => 486, "country_id" => 36, "name" => "Maltahohe"];
        $regions[] = ["id" => 487, "country_id" => 36, "name" => "Mariental"];
        $regions[] = ["id" => 488, "country_id" => 36, "name" => "Ohangwena"];
        $regions[] = ["id" => 489, "country_id" => 36, "name" => "Okahandja"];
        $regions[] = ["id" => 490, "country_id" => 36, "name" => "Okavango"];
        $regions[] = ["id" => 491, "country_id" => 36, "name" => "Omaheke"];
        $regions[] = ["id" => 492, "country_id" => 36, "name" => "Omaruru"];
        $regions[] = ["id" => 493, "country_id" => 36, "name" => "Omusati"];
        $regions[] = ["id" => 494, "country_id" => 36, "name" => "Oshana"];
        $regions[] = ["id" => 495, "country_id" => 36, "name" => "Oshikoto"];
        $regions[] = ["id" => 496, "country_id" => 36, "name" => "Otjiwarongo"];
        $regions[] = ["id" => 497, "country_id" => 36, "name" => "Otjozondjupa"];
        $regions[] = ["id" => 498, "country_id" => 36, "name" => "Outjo"];
        $regions[] = ["id" => 499, "country_id" => 36, "name" => "Rehoboth"];
        $regions[] = ["id" => 500, "country_id" => 36, "name" => "Swakopmund"];
        $regions[] = ["id" => 501, "country_id" => 36, "name" => "Tsumeb"];
        $regions[] = ["id" => 502, "country_id" => 36, "name" => "Windhoek"];
        $regions[] = ["id" => 503, "country_id" => 37, "name" => "Agadez"];
        $regions[] = ["id" => 504, "country_id" => 37, "name" => "Diffa"];
        $regions[] = ["id" => 505, "country_id" => 37, "name" => "Dosso"];
        $regions[] = ["id" => 506, "country_id" => 37, "name" => "Maradi"];
        $regions[] = ["id" => 507, "country_id" => 37, "name" => "Niamey"];
        $regions[] = ["id" => 508, "country_id" => 37, "name" => "Tahoua"];
        $regions[] = ["id" => 509, "country_id" => 37, "name" => "Zinder"];
        $regions[] = ["id" => 510, "country_id" => 38, "name" => "Abia"];
        $regions[] = ["id" => 511, "country_id" => 38, "name" => "Adamawa"];
        $regions[] = ["id" => 512, "country_id" => 38, "name" => "Akwa Ibom"];
        $regions[] = ["id" => 513, "country_id" => 38, "name" => "Anambra"];
        $regions[] = ["id" => 514, "country_id" => 38, "name" => "Bauchi"];
        $regions[] = ["id" => 515, "country_id" => 38, "name" => "Bayelsa"];
        $regions[] = ["id" => 516, "country_id" => 38, "name" => "Benue"];
        $regions[] = ["id" => 517, "country_id" => 38, "name" => "Borno"];
        $regions[] = ["id" => 518, "country_id" => 38, "name" => "Cross River"];
        $regions[] = ["id" => 519, "country_id" => 38, "name" => "Delta"];
        $regions[] = ["id" => 520, "country_id" => 38, "name" => "Ebonyi"];
        $regions[] = ["id" => 521, "country_id" => 38, "name" => "Edo"];
        $regions[] = ["id" => 522, "country_id" => 38, "name" => "Ekiti"];
        $regions[] = ["id" => 523, "country_id" => 38, "name" => "Enugu"];
        $regions[] = ["id" => 524, "country_id" => 38, "name" => "Federal Capital Territory"];
        $regions[] = ["id" => 525, "country_id" => 38, "name" => "Gombe"];
        $regions[] = ["id" => 526, "country_id" => 38, "name" => "Imo"];
        $regions[] = ["id" => 527, "country_id" => 38, "name" => "Jigawa"];
        $regions[] = ["id" => 528, "country_id" => 38, "name" => "Kaduna"];
        $regions[] = ["id" => 529, "country_id" => 38, "name" => "Kano"];
        $regions[] = ["id" => 530, "country_id" => 38, "name" => "Katsina"];
        $regions[] = ["id" => 531, "country_id" => 38, "name" => "Kebbi"];
        $regions[] = ["id" => 532, "country_id" => 38, "name" => "Kogi"];
        $regions[] = ["id" => 533, "country_id" => 38, "name" => "Kwara"];
        $regions[] = ["id" => 534, "country_id" => 38, "name" => "Lagos"];
        $regions[] = ["id" => 535, "country_id" => 38, "name" => "Nassarawa"];
        $regions[] = ["id" => 536, "country_id" => 38, "name" => "Niger"];
        $regions[] = ["id" => 537, "country_id" => 38, "name" => "Ogun"];
        $regions[] = ["id" => 538, "country_id" => 38, "name" => "Ondo"];
        $regions[] = ["id" => 539, "country_id" => 38, "name" => "Osun"];
        $regions[] = ["id" => 540, "country_id" => 38, "name" => "Oyo"];
        $regions[] = ["id" => 541, "country_id" => 38, "name" => "Plateau"];
        $regions[] = ["id" => 542, "country_id" => 38, "name" => "Rivers"];
        $regions[] = ["id" => 543, "country_id" => 38, "name" => "Sokoto"];
        $regions[] = ["id" => 544, "country_id" => 38, "name" => "Taraba"];
        $regions[] = ["id" => 545, "country_id" => 38, "name" => "Yobe"];
        $regions[] = ["id" => 546, "country_id" => 38, "name" => "Zamfara"];
        $regions[] = ["id" => 547, "country_id" => 39, "name" => "Butare"];
        $regions[] = ["id" => 548, "country_id" => 39, "name" => "Est"];
        $regions[] = ["id" => 549, "country_id" => 39, "name" => "Gitarama"];
        $regions[] = ["id" => 550, "country_id" => 39, "name" => "Kibungo"];
        $regions[] = ["id" => 551, "country_id" => 39, "name" => "Kigali"];
        $regions[] = ["id" => 552, "country_id" => 39, "name" => "Nord"];
        $regions[] = ["id" => 553, "country_id" => 39, "name" => "Ouest"];
        $regions[] = ["id" => 554, "country_id" => 39, "name" => "Sud"];
        $regions[] = ["id" => 555, "country_id" => 40, "name" => "Príncipe"];
        $regions[] = ["id" => 556, "country_id" => 40, "name" => "São Tomé"];
        $regions[] = ["id" => 557, "country_id" => 41, "name" => "Dakar"];
        $regions[] = ["id" => 558, "country_id" => 41, "name" => "Diourbel"];
        $regions[] = ["id" => 559, "country_id" => 41, "name" => "Fatick"];
        $regions[] = ["id" => 560, "country_id" => 41, "name" => "Kaolack"];
        $regions[] = ["id" => 561, "country_id" => 41, "name" => "Kolda"];
        $regions[] = ["id" => 562, "country_id" => 41, "name" => "Louga"];
        $regions[] = ["id" => 563, "country_id" => 41, "name" => "Matam"];
        $regions[] = ["id" => 564, "country_id" => 41, "name" => "Saint-Louis"];
        $regions[] = ["id" => 565, "country_id" => 41, "name" => "Tambacounda"];
        $regions[] = ["id" => 566, "country_id" => 41, "name" => "Thiès"];
        $regions[] = ["id" => 567, "country_id" => 41, "name" => "Ziguinchor"];
        $regions[] = ["id" => 568, "country_id" => 42, "name" => "Anse Boileau"];
        $regions[] = ["id" => 569, "country_id" => 42, "name" => "Beau Vallon"];
        $regions[] = ["id" => 570, "country_id" => 42, "name" => "Takamaka"];
        $regions[] = ["id" => 571, "country_id" => 42, "name" => "Victoria"];
        $regions[] = ["id" => 572, "country_id" => 42, "name" => "Grand Anse Mahe"];
        $regions[] = ["id" => 573, "country_id" => 43, "name" => "Eastern"];
        $regions[] = ["id" => 574, "country_id" => 43, "name" => "Northern"];
        $regions[] = ["id" => 575, "country_id" => 43, "name" => "Southern"];
        $regions[] = ["id" => 576, "country_id" => 43, "name" => "Western Area"];
        $regions[] = ["id" => 577, "country_id" => 44, "name" => "Banaadir"];
        $regions[] = ["id" => 578, "country_id" => 44, "name" => "Woqooyi Galbeed"];
        $regions[] = ["id" => 579, "country_id" => 44, "name" => "Jubbada Hoose"];
        $regions[] = ["id" => 580, "country_id" => 44, "name" => "Shabeellaha Hoose"];
        $regions[] = ["id" => 581, "country_id" => 44, "name" => "Bari"];
        $regions[] = ["id" => 582, "country_id" => 44, "name" => "Nugaal"];
        $regions[] = ["id" => 583, "country_id" => 44, "name" => "Shabeellaha Dhexe"];
        $regions[] = ["id" => 584, "country_id" => 44, "name" => "Jubbada Dhexe"];
        $regions[] = ["id" => 585, "country_id" => 44, "name" => "Bakool"];
        $regions[] = ["id" => 586, "country_id" => 44, "name" => "Bay"];
        $regions[] = ["id" => 587, "country_id" => 44, "name" => "Mudug"];
        $regions[] = ["id" => 588, "country_id" => 44, "name" => "Galguduud"];
        $regions[] = ["id" => 589, "country_id" => 44, "name" => "Sanaag"];
        $regions[] = ["id" => 590, "country_id" => 44, "name" => "Hiiraan"];
        $regions[] = ["id" => 591, "country_id" => 44, "name" => "Gedo"];
        $regions[] = ["id" => 592, "country_id" => 45, "name" => "Eastern Cape"];
        $regions[] = ["id" => 593, "country_id" => 45, "name" => "Free State"];
        $regions[] = ["id" => 594, "country_id" => 45, "name" => "Gauteng"];
        $regions[] = ["id" => 595, "country_id" => 45, "name" => "KwaZulu-Natal"];
        $regions[] = ["id" => 596, "country_id" => 45, "name" => "Limpopo"];
        $regions[] = ["id" => 597, "country_id" => 45, "name" => "Mpumalanga"];
        $regions[] = ["id" => 598, "country_id" => 45, "name" => "Northern Cape"];
        $regions[] = ["id" => 599, "country_id" => 45, "name" => "North-West"];
        $regions[] = ["id" => 600, "country_id" => 45, "name" => "North-Western Province"];
        $regions[] = ["id" => 601, "country_id" => 45, "name" => "Western Cape"];
        $regions[] = ["id" => 602, "country_id" => 46, "name" => "Amadi"];
        $regions[] = ["id" => 603, "country_id" => 46, "name" => "Aweil"];
        $regions[] = ["id" => 604, "country_id" => 46, "name" => "Aweil East"];
        $regions[] = ["id" => 605, "country_id" => 46, "name" => "Boma"];
        $regions[] = ["id" => 606, "country_id" => 46, "name" => "Eastern Bieh"];
        $regions[] = ["id" => 607, "country_id" => 46, "name" => "Eastern Lakes"];
        $regions[] = ["id" => 608, "country_id" => 46, "name" => "Eastern Nile"];
        $regions[] = ["id" => 609, "country_id" => 46, "name" => "Gbudwe"];
        $regions[] = ["id" => 610, "country_id" => 46, "name" => "Gogrial"];
        $regions[] = ["id" => 611, "country_id" => 46, "name" => "Gok"];
        $regions[] = ["id" => 612, "country_id" => 46, "name" => "Imatong"];
        $regions[] = ["id" => 613, "country_id" => 46, "name" => "Jonglei"];
        $regions[] = ["id" => 614, "country_id" => 46, "name" => "Jubek"];
        $regions[] = ["id" => 615, "country_id" => 46, "name" => "Latjoor"];
        $regions[] = ["id" => 616, "country_id" => 46, "name" => "Lol"];
        $regions[] = ["id" => 617, "country_id" => 46, "name" => "Maridi"];
        $regions[] = ["id" => 618, "country_id" => 46, "name" => "Namorunyang"];
        $regions[] = ["id" => 619, "country_id" => 46, "name" => "Northern Liech"];
        $regions[] = ["id" => 620, "country_id" => 46, "name" => "Ruweng"];
        $regions[] = ["id" => 621, "country_id" => 46, "name" => "Southern Liech"];
        $regions[] = ["id" => 622, "country_id" => 46, "name" => "Terekeka"];
        $regions[] = ["id" => 623, "country_id" => 46, "name" => "Tonj"];
        $regions[] = ["id" => 624, "country_id" => 46, "name" => "Twic"];
        $regions[] = ["id" => 625, "country_id" => 46, "name" => "Wau"];
        $regions[] = ["id" => 626, "country_id" => 46, "name" => "Western Bieh"];
        $regions[] = ["id" => 627, "country_id" => 46, "name" => "Western Lakes"];
        $regions[] = ["id" => 628, "country_id" => 46, "name" => "Western Nile"];
        $regions[] = ["id" => 629, "country_id" => 46, "name" => "Yei River"];
        $regions[] = ["id" => 630, "country_id" => 47, "name" => "Al Istiwa'iyah"];
        $regions[] = ["id" => 631, "country_id" => 47, "name" => "Al Khartum"];
        $regions[] = ["id" => 632, "country_id" => 47, "name" => "Al Wahadah State"];
        $regions[] = ["id" => 633, "country_id" => 47, "name" => "Al Wusta"];
        $regions[] = ["id" => 634, "country_id" => 47, "name" => "Ash Shamaliyah"];
        $regions[] = ["id" => 635, "country_id" => 47, "name" => "Ash Sharqiyah"];
        $regions[] = ["id" => 636, "country_id" => 47, "name" => "Bahr al Ghazal"];
        $regions[] = ["id" => 637, "country_id" => 47, "name" => "Central Equatoria State"];
        $regions[] = ["id" => 638, "country_id" => 47, "name" => "Darfur"];
        $regions[] = ["id" => 639, "country_id" => 47, "name" => "Kurdufan"];
        $regions[] = ["id" => 640, "country_id" => 47, "name" => "Upper Nile"];
        $regions[] = ["id" => 641, "country_id" => 48, "name" => "Hhohho"];
        $regions[] = ["id" => 642, "country_id" => 48, "name" => "Lubombo"];
        $regions[] = ["id" => 643, "country_id" => 48, "name" => "Manzini"];
        $regions[] = ["id" => 644, "country_id" => 48, "name" => "Shiselweni"];
        $regions[] = ["id" => 645, "country_id" => 49, "name" => "Arusha"];
        $regions[] = ["id" => 646, "country_id" => 49, "name" => "Dar es Salaam"];
        $regions[] = ["id" => 647, "country_id" => 49, "name" => "Dodoma"];
        $regions[] = ["id" => 648, "country_id" => 49, "name" => "Iringa"];
        $regions[] = ["id" => 649, "country_id" => 49, "name" => "Kagera"];
        $regions[] = ["id" => 650, "country_id" => 49, "name" => "Kigoma"];
        $regions[] = ["id" => 651, "country_id" => 49, "name" => "Kilimanjaro"];
        $regions[] = ["id" => 652, "country_id" => 49, "name" => "Lindi"];
        $regions[] = ["id" => 653, "country_id" => 49, "name" => "Manyara"];
        $regions[] = ["id" => 654, "country_id" => 49, "name" => "Mara"];
        $regions[] = ["id" => 655, "country_id" => 49, "name" => "Mbeya"];
        $regions[] = ["id" => 656, "country_id" => 49, "name" => "Morogoro"];
        $regions[] = ["id" => 657, "country_id" => 49, "name" => "Mtwara"];
        $regions[] = ["id" => 658, "country_id" => 49, "name" => "Mwanza"];
        $regions[] = ["id" => 659, "country_id" => 49, "name" => "Pemba North"];
        $regions[] = ["id" => 660, "country_id" => 49, "name" => "Pemba South"];
        $regions[] = ["id" => 661, "country_id" => 49, "name" => "Pwani"];
        $regions[] = ["id" => 662, "country_id" => 49, "name" => "Rukwa"];
        $regions[] = ["id" => 663, "country_id" => 49, "name" => "Ruvuma"];
        $regions[] = ["id" => 664, "country_id" => 49, "name" => "Shinyanga"];
        $regions[] = ["id" => 665, "country_id" => 49, "name" => "Singida"];
        $regions[] = ["id" => 666, "country_id" => 49, "name" => "Tabora"];
        $regions[] = ["id" => 667, "country_id" => 49, "name" => "Tanga"];
        $regions[] = ["id" => 668, "country_id" => 49, "name" => "Zanzibar Central"];
        $regions[] = ["id" => 669, "country_id" => 49, "name" => "Zanzibar North"];
        $regions[] = ["id" => 670, "country_id" => 49, "name" => "Zanzibar Urban"];
        $regions[] = ["id" => 671, "country_id" => 50, "name" => "Centrale"];
        $regions[] = ["id" => 672, "country_id" => 50, "name" => "Kara"];
        $regions[] = ["id" => 673, "country_id" => 50, "name" => "Maritime"];
        $regions[] = ["id" => 674, "country_id" => 50, "name" => "Plateaux"];
        $regions[] = ["id" => 675, "country_id" => 50, "name" => "Savanes"];
        $regions[] = ["id" => 676, "country_id" => 51, "name" => "Aiana"];
        $regions[] = ["id" => 677, "country_id" => 51, "name" => "Al Mahdia"];
        $regions[] = ["id" => 678, "country_id" => 51, "name" => "Al Munastīr"];
        $regions[] = ["id" => 679, "country_id" => 51, "name" => "Bājah"];
        $regions[] = ["id" => 680, "country_id" => 51, "name" => "Ben Arous"];
        $regions[] = ["id" => 681, "country_id" => 51, "name" => "Bizerte"];
        $regions[] = ["id" => 682, "country_id" => 51, "name" => "El Kef"];
        $regions[] = ["id" => 683, "country_id" => 51, "name" => "Gabes"];
        $regions[] = ["id" => 684, "country_id" => 51, "name" => "Jendouba"];
        $regions[] = ["id" => 685, "country_id" => 51, "name" => "Kairouan"];
        $regions[] = ["id" => 686, "country_id" => 51, "name" => "Kasserine"];
        $regions[] = ["id" => 687, "country_id" => 51, "name" => "Kebili"];
        $regions[] = ["id" => 688, "country_id" => 51, "name" => "Madanīn"];
        $regions[] = ["id" => 689, "country_id" => 51, "name" => "Manouba"];
        $regions[] = ["id" => 690, "country_id" => 51, "name" => "Nabeul"];
        $regions[] = ["id" => 691, "country_id" => 51, "name" => "Qafşah"];
        $regions[] = ["id" => 692, "country_id" => 51, "name" => "Sfax"];
        $regions[] = ["id" => 693, "country_id" => 51, "name" => "Sidi Bou Zid"];
        $regions[] = ["id" => 694, "country_id" => 51, "name" => "Siliana"];
        $regions[] = ["id" => 695, "country_id" => 51, "name" => "Sousse"];
        $regions[] = ["id" => 696, "country_id" => 51, "name" => "Tataouine"];
        $regions[] = ["id" => 697, "country_id" => 51, "name" => "Tozeur"];
        $regions[] = ["id" => 698, "country_id" => 51, "name" => "Tūnis"];
        $regions[] = ["id" => 699, "country_id" => 51, "name" => "Zaghouan"];
        $regions[] = ["id" => 700, "country_id" => 52, "name" => "Adjumani"];
        $regions[] = ["id" => 701, "country_id" => 52, "name" => "Apac"];
        $regions[] = ["id" => 702, "country_id" => 52, "name" => "Arua"];
        $regions[] = ["id" => 703, "country_id" => 52, "name" => "Bugiri"];
        $regions[] = ["id" => 704, "country_id" => 52, "name" => "Bundibugyo"];
        $regions[] = ["id" => 705, "country_id" => 52, "name" => "Bushenyi"];
        $regions[] = ["id" => 706, "country_id" => 52, "name" => "Busia"];
        $regions[] = ["id" => 707, "country_id" => 52, "name" => "Gulu"];
        $regions[] = ["id" => 708, "country_id" => 52, "name" => "Hoima"];
        $regions[] = ["id" => 709, "country_id" => 52, "name" => "Iganga"];
        $regions[] = ["id" => 710, "country_id" => 52, "name" => "Jinja"];
        $regions[] = ["id" => 711, "country_id" => 52, "name" => "Kabarole"];
        $regions[] = ["id" => 712, "country_id" => 52, "name" => "Kaberamaido"];
        $regions[] = ["id" => 713, "country_id" => 52, "name" => "Kalangala"];
        $regions[] = ["id" => 714, "country_id" => 52, "name" => "Kampala"];
        $regions[] = ["id" => 715, "country_id" => 52, "name" => "Kamuli"];
        $regions[] = ["id" => 716, "country_id" => 52, "name" => "Kamwenge"];
        $regions[] = ["id" => 717, "country_id" => 52, "name" => "Kanungu"];
        $regions[] = ["id" => 718, "country_id" => 52, "name" => "Kapchorwa"];
        $regions[] = ["id" => 719, "country_id" => 52, "name" => "Kasese"];
        $regions[] = ["id" => 720, "country_id" => 52, "name" => "Katakwi"];
        $regions[] = ["id" => 721, "country_id" => 52, "name" => "Kayunga"];
        $regions[] = ["id" => 722, "country_id" => 52, "name" => "Kibale"];
        $regions[] = ["id" => 723, "country_id" => 52, "name" => "Kiboga"];
        $regions[] = ["id" => 724, "country_id" => 52, "name" => "Kisoro"];
        $regions[] = ["id" => 725, "country_id" => 52, "name" => "Kitgum"];
        $regions[] = ["id" => 726, "country_id" => 52, "name" => "Kotido"];
        $regions[] = ["id" => 727, "country_id" => 52, "name" => "Kumi"];
        $regions[] = ["id" => 728, "country_id" => 52, "name" => "Kyenjojo"];
        $regions[] = ["id" => 729, "country_id" => 52, "name" => "Lira"];
        $regions[] = ["id" => 730, "country_id" => 52, "name" => "Luwero"];
        $regions[] = ["id" => 731, "country_id" => 52, "name" => "Masaka"];
        $regions[] = ["id" => 732, "country_id" => 52, "name" => "Masindi"];
        $regions[] = ["id" => 733, "country_id" => 52, "name" => "Mayuge"];
        $regions[] = ["id" => 734, "country_id" => 52, "name" => "Mbale"];
        $regions[] = ["id" => 735, "country_id" => 52, "name" => "Mbarara"];
        $regions[] = ["id" => 736, "country_id" => 52, "name" => "Moroto"];
        $regions[] = ["id" => 737, "country_id" => 52, "name" => "Moyo"];
        $regions[] = ["id" => 738, "country_id" => 52, "name" => "Mpigi"];
        $regions[] = ["id" => 739, "country_id" => 52, "name" => "Mubende"];
        $regions[] = ["id" => 740, "country_id" => 52, "name" => "Mukono"];
        $regions[] = ["id" => 741, "country_id" => 52, "name" => "Nakapiripirit"];
        $regions[] = ["id" => 742, "country_id" => 52, "name" => "Nakasongola"];
        $regions[] = ["id" => 743, "country_id" => 52, "name" => "Nebbi"];
        $regions[] = ["id" => 744, "country_id" => 52, "name" => "Ntungamo"];
        $regions[] = ["id" => 745, "country_id" => 52, "name" => "Pader"];
        $regions[] = ["id" => 746, "country_id" => 52, "name" => "Pallisa"];
        $regions[] = ["id" => 747, "country_id" => 52, "name" => "Rakai"];
        $regions[] = ["id" => 748, "country_id" => 52, "name" => "Rukungiri"];
        $regions[] = ["id" => 749, "country_id" => 52, "name" => "Sembabule"];
        $regions[] = ["id" => 750, "country_id" => 52, "name" => "Sironko"];
        $regions[] = ["id" => 751, "country_id" => 52, "name" => "Soroti"];
        $regions[] = ["id" => 752, "country_id" => 52, "name" => "Tororo"];
        $regions[] = ["id" => 753, "country_id" => 52, "name" => "Wakiso"];
        $regions[] = ["id" => 754, "country_id" => 52, "name" => "Yumbe"];
        $regions[] = ["id" => 755, "country_id" => 53, "name" => "Central"];
        $regions[] = ["id" => 756, "country_id" => 53, "name" => "Copperbelt"];
        $regions[] = ["id" => 757, "country_id" => 53, "name" => "Eastern"];
        $regions[] = ["id" => 758, "country_id" => 53, "name" => "Luapula"];
        $regions[] = ["id" => 759, "country_id" => 53, "name" => "Lusaka"];
        $regions[] = ["id" => 760, "country_id" => 53, "name" => "Northern"];
        $regions[] = ["id" => 761, "country_id" => 53, "name" => "North-Western"];
        $regions[] = ["id" => 762, "country_id" => 53, "name" => "Southern"];
        $regions[] = ["id" => 763, "country_id" => 53, "name" => "Western"];
        $regions[] = ["id" => 764, "country_id" => 54, "name" => "Bulawayo"];
        $regions[] = ["id" => 765, "country_id" => 54, "name" => "Harare"];
        $regions[] = ["id" => 766, "country_id" => 54, "name" => "Manicaland"];
        $regions[] = ["id" => 767, "country_id" => 54, "name" => "Mashonaland Central"];
        $regions[] = ["id" => 768, "country_id" => 54, "name" => "Mashonaland East"];
        $regions[] = ["id" => 769, "country_id" => 54, "name" => "Mashonaland West"];
        $regions[] = ["id" => 770, "country_id" => 54, "name" => "Masvingo"];
        $regions[] = ["id" => 771, "country_id" => 54, "name" => "Matabeleland North"];
        $regions[] = ["id" => 772, "country_id" => 54, "name" => "Matabeleland South"];
        $regions[] = ["id" => 773, "country_id" => 54, "name" => "Midlands"];

        DB::table('states')->insert($regions);

        DB::statement('SET FOREIGN_KEY_CHECKS=1');
    }
}
